spring:
  redis:
    database: 0
    host: ${REDIS_HOST:140.124.181.60}
    port: ${REDIS_PORT:31486}
  hbase:
    zookeeper:
      quorum: ${HBASE_ZOOKEEPER_QUORUM:localhost:2181}
      znode.parent: ${HBASE_ZOOKEEPER_ZNODE_PARENT:/hbase}
    rootdir: ${HBASE_ROOTDIR:file:///Users/wei/Downloads/hbase-2.1.1/data}
